### ISSUE TITLE
Fix multiple shares

### ISSUE THREAD

**Issue by justinc1** [robertdebock/ansible-role-nfsserver#2]
## Describe the bug

The multiple shares case is not fixed yet (#1).
The exports.j2 template is still missing one empty line, to get newline in rendered /etc/exports.

The fixed exports.j2 is:
```
(.venv) justin_cinkelj@jcpc:~/devel/$ cat roles/robertdebock.nfsserver/templates/exports.j2
{{ ansible_managed | comment }}

{% for export in nfsserver_exports %}
{{ export.share }} {% for host in export.hosts %}{{ host.name }}({% for option in host.options %}{{ option }}{% if not loop.last %},{% endif %}{% endfor %}) {% endfor %}

{% endfor %}
(.venv) justin_cinkelj@jcpc:~/devel/$ 
```

**Comment by seberm** [comment]
Hello @robertdebock,
would it be possible to fix it? I think this is very quick and safe change.

Thanks a lot!

**Comment by robertdebock** [comment]
Sorry I missed this, I'll pay this issue some attention.

**Comment by seberm** [comment]
No problem.

I can see that you fixed the bug (https://github.com/robertdebock/ansible-role-nfsserver/commit/d77fdc3b06c63b3085f4588175036abb7ff0f87f), I think we can close this issue.

And by the way - thanks for your great work on ansible roles!
